EIP Creation Fails in Region Where EC2-Classic is Available
jaredhocutt/openshift-provision pull request #11
Opened 2018-08-21 23:36 UTC by jcullet

#### What's this PR do?

When running the provision command in an account/region where ec2-classic is available, the EIPs are created with standard networking (not VPC) and fail to attach to the EC2 instances.

#### Where should the reviewer start?

Review the documentation and cxhange to the ec2.yml tasks file to add in_vpc: true.

#### How should this be manually tested?

An account/region with ec2-classic available must be used to test the error. Any account can be used to test for the regression case.

#### Any background context you want to provide?

I ran into this issue in my account, which has the following supported:

![screenshot from 2018-08-21 19-20-22](https://user-images.githubusercontent.com/244013/44434510-748fb100-a579-11e8-815e-e2b7a11edee0.png)

2018-08-21 23:49 UTC, jaredhocutt requested changes
Change looks good, just minor fix to re-add blank newline at the end of the file.

2018-08-21 23:49 UTC, jaredhocutt commented on playbooks/roles/provision_aws/tasks/ec2.yml
> +    - "{{ ec2_create_infra_instance.instances | map(attribute='instance_id') | list }}"
Add single newline at end of the file.

2018-08-21 23:57 UTC, jcullet commented
Updated with a newline at the end of the file.

2018-08-22 00:00 UTC, jaredhocutt approved these changes

2018-08-22 00:00 UTC, merged